### ISSUE TITLE
Delete this, github is not a blog

### ISSUE THREAD

**Issue by hikaruAi** [sdmg15/Best-websites-a-programmer-should-visit#102]
Maybe you could add a real coding project to your "lists-only" account.
Blogger.com is free.

**Comment by Jahhein** [comment]
Github is a place for projects. Projects that are open to the public to contribute to, to help others. over 10,000 people have enjoyed this repository. 

https://github.com/sindresorhus/awesome This is also a "List-only" repository with almost 60,000 stars.

You are in the wrong for posting this issue. Please delete it.

**Comment by hsoj95** [comment]
I feel as though this comment was meant to only be hurtful towards the owner of the project. There are many non-code based projects on GitHub, including list, code of conducts, and other style projects. There is even a section featured by GitHub itself for community sourcing politics.

Comments like this serve no constructive basis, and have no place on sites like GitHub.
