### ISSUE TITLE
Add [Youtube channel] : Two Minute Papers

### ISSUE THREAD

**Issue by piyushmohan01** [sdmg15/Best-websites-a-programmer-should-visit#1054]
- Videos reviewing state-of-the-art ML/AI Research Papers
- Perfect destination to know more about the current state in the field.
- Link to the Youtube channel : [Two Minute Papers](https://www.youtube.com/c/K%C3%A1rolyZsolnai/featured)

**Comment by CAG07** [comment]
This Issue can be closed now
