### ISSUE TITLE
Summer Internship: The Ultimate Guide is unavailable 

### ISSUE THREAD

**Issue by codeshef** [sdmg15/Best-websites-a-programmer-should-visit#110]
Page not found

**Comment by palash25** [comment]
I think we should add a new section to the list like **Jobs and Internships** I would like to contribute a few links to that.

**Comment by sdmg15** [comment]
Yeah that's a good idea @palash25

**Comment by lalitmee** [comment]
@palash25 I have added sections **Jobs and Internships**. Now you can contribute those few links. :+1:
