### ISSUE TITLE
Add more "Coding practice for beginners"...

### ISSUE THREAD

**Issue by doriel** [sdmg15/Best-websites-a-programmer-should-visit#119]
Please add more codding schools like https://dash.generalassemb.ly/, https://www.khanacademy.org/hourofcode, https://codecombat.com/ or even this one https://scratch.mit.edu/.

**Comment by sdmg15** [comment]
A PR should be welcomed.

**Comment by doriel** [comment]
Ok... But i see that you already have to many PR's...

**Comment by sdmg15** [comment]
No problem you can PR it :wink:
