### ISSUE TITLE
How about new category "Web Services" (REST API, Web API etc)?

### ISSUE THREAD

**Issue by Dingo64** [sdmg15/Best-websites-a-programmer-should-visit#131]
Web APIs can be used in pretty much every language so they are very useful. Here are some collections of APIs I find interesting:

1) https://algorithmia.com/algorithms 
They have a free package with 5000 credits every month. Some API calls require more than 1 credit. 

2) http://rest7.com/
Here all the APIs are free to use. No registration needed (or even possible). No paid plans.

3) https://market.mashape.com/explore
Some APIs are free, some are paid. Seems they have more functions than the above 2 together but most of the APIs here are paid.

**Comment by sdmg15** [comment]
Hey you can embed the section and make a PR !
thx.
