### ISSUE TITLE
Enforce contributing guidelines

### ISSUE THREAD

**Issue by miguelpalazzo** [sdmg15/Best-websites-a-programmer-should-visit#1368]
I've noticed in some closed Pull Requests that the [contributing guidelines](../blob/master/CONTRIBUTING.md) might be misleading at the moment due to cases that can reflect on:
- Just one link per PR allowed (instead of the stated `Only one or two links per Pull Requests`).
- No more YouTube channels allowed.
- Something else to be added as rule of thumb.

To avoid that, it might be updated, while also introducing a Pull Request template to make sure the code review and merging experience could be much easier, as I know this process can be taxing, especially now with Hacktoberfest ongoing.

**Comment by sdmg15** [comment]
@miguelpalazzo Yeah that will be a really good think. If you can do it sounds good

**Comment by miguelpalazzo** [comment]
Right away!

**Comment by miguelpalazzo** [comment]
@sdmg15 if you need help reviewing PRs accordingly, I could gladly do that a few hours a day. Just let me know how to do so. Thanks!
