### ISSUE TITLE
I want to build a better website for it.

### ISSUE THREAD

**Issue by ghost** [sdmg15/Best-websites-a-programmer-should-visit#153]
![new](https://user-images.githubusercontent.com/25458566/27260335-ff52a8da-545b-11e7-98d3-c252e45c51e1.png)

A better website will be build after few days. 

I want to know if you want to add it to gh-pages?

**Comment by sdmg15** [comment]
Hey is the website ready?

**Comment by PsiACE** [comment]
I changed my mind so that it could work better as a jekyll theme,.Delivery in two days

**Comment by Tr4pSt3R** [comment]
@PsiACE can you share the repo so that we can contribute to it please?

**Comment by ityler** [comment]
@PsiACE @Tr4pSt3R I completely agree the website should only be part of/mentioned in this git repo if the website is fully open source as well.

**Comment by PsiACE** [comment]
I have test it on windows successfully
However, when it worked on github pages, there are some mistakes.
I think that I need help.
repo url : https://github.com/PsiACE/Best-websites-a-programmer-should-visit/tree/gh-pages

**Comment by PsiACE** [comment]
On My Computer
![windows](https://user-images.githubusercontent.com/25458566/27798986-0d0d340e-6046-11e7-8b72-bde20cd5fc60.png)
On GitHub Pages
![github](https://user-images.githubusercontent.com/25458566/27799002-1cdf7770-6046-11e7-9165-5bcd8328b638.png)

**Comment by ityler** [comment]
Link for those who needed it, aka myself: https://psiace.github.io/Best-websites-a-programmer-should-visit/

**Comment by ityler** [comment]
The (margin-left: auto & margin-right: auto) is applied to the container class that is assigned to the top level div for the entire page. From your first screen shit it looks like this is only being applied to the content starting at "Website is ready".

**Comment by sdmg15** [comment]
Good view. There are some duplicates, hope this should be fixed. And also I think the first header should be in one-line?

**Comment by ityler** [comment]
I love the idea of having a site that's a little more user friendly than scrolling through a repo Readme doc. I do hope we are able to setup a way to programmatically update the sites resources without having to manually add every change or fix that comes through the repo. Forgive me if that's already the idea as i'm not super familiar with "Github pages" but I am interested in learning more about pages and helping if possible.

**Comment by PsiACE** [comment]
HTML Verson is Okay. You can view it  https : //psiace.github.io/Best-websites-a-programmer-should-visit/

**Comment by PsiACE** [comment]
[Best-websites-a-programmer-should-visit.zip](https://github.com/sdmg15/Best-websites-a-programmer-should-visit/files/1121736/Best-websites-a-programmer-should-visit.zip)
You can add it to a github page, but it isn't the newest verson.

**Comment by ityler** [comment]
I am going to be taking a look at this shortly to see how best to integrate it into the current repo.

**Comment by cyberboysumanjay** [comment]
I also made one for my simplicity. Have a look http://sumanjay.me/pw/

**Comment by madarsbiss** [comment]
would be nice if all the resources would open in new tabs, that way we do not need to right click
