### ISSUE TITLE
Removing trailling slash

### ISSUE THREAD

**Issue by sdmg15** [sdmg15/Best-websites-a-programmer-should-visit#165]
@sindresorhus hello, 
I'm facing this issue with the awesome-lint, please assist me on how to solve it.
thanks.

**Comment by ityler** [comment]
What exactly is the issue? Do we want the trailing slash functionality removed from the linter?

**Comment by sdmg15** [comment]
Wasn't aware on what it was, but through some of PR the issue was solved.
