### ISSUE TITLE
Programming Principles

### ISSUE THREAD

**Issue by webpro** [sdmg15/Best-websites-a-programmer-should-visit#174]
Nice overview. I saw [The Principles of Good Programming](http://www.artima.com/weblogs/viewpost.jsp?thread=331531). Based on this, I once did [Programming Principles](https://github.com/webpro/programming-principles) (or http://webpro.github.io/programming-principles/). It isn't original, but people may find it a bit easier to scan, there is more structure and other resources. Up to you: ignore/replace/add. Anything goes!

**Comment by sdmg15** [comment]
Hey ! 
You can make a PR if you think some changes need to be made;

**Comment by snsj369** [comment]
ok
