### ISSUE TITLE
FIx broken link in README.md

### ISSUE THREAD

**Issue by Eaglesight02** [sdmg15/Best-websites-a-programmer-should-visit#1897]
- There is a broken link under the __"Good Articles"__ section:
    - [What every programmer should know about memory - PDF](http://futuretech.blinkenlights.nl/misc/cpumemory.pdf)
- This link is not reachable and is broken:
![image](https://github.com/sdmg15/Best-websites-a-programmer-should-visit/assets/108081278/416a01c4-2e6e-4bf5-b828-95426d760eaa)
- A working alternative must be provided.

**Comment by hey-granth** [comment]
this issue has been fixed.
