### ISSUE TITLE
Internships Section: Two Links Not Working, Please Update

### ISSUE THREAD

**Issue by csengineer1990** [sdmg15/Best-websites-a-programmer-should-visit#1959]
The following two links are not working:

1. [Letsintern](https://www.letsintern.com/) : Get a smart and challenging internship for you from the LetsIntern.
2. [PerfectIntern](https://www.perfectintern.com/): Get help finding a paid internship, resume prep, interview prep, and more!

It seems the URLs for these links may have changed. Upon checking, I found the following updated addresses:

1. [Letsintern] (https://letsintern.in/)
2. [PerfectIntern] (https://www.theperfectintern.co.ke/)

**Comment by csengineer1990** [comment]
Hi, I came across this issue while exploring the repository, and I believe I can resolve it. I would love the opportunity to work on this with your guidance. Could you kindly assign this issue to me?

Thank you so much!

**Comment by dishant702** [comment]
hey @csengineer1990  the address you provided for the perfectIntern is also not working, may be there is some updates in this address

**Comment by csengineer1990** [comment]
Yes, that could be the case. The last time I checked, it was working fine, but it's possible they’ve made some updates since then.

**Comment by csengineer1990** [comment]
Hi, may I make changes to the internship section, or would you prefer any specific suggestions? Please assign this issue to me with the Hacktoberfest label if possible.
