### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by MLescaudron** [sdmg15/Best-websites-a-programmer-should-visit#201]
Hi, 
https://learn-anything.xyz/ -> dead actually
https://github.com/sdmg15/Best-websites-a-programmer-should-visit/blob/master/vorillaz.github.io/devicons -> 404

**Comment by sdmg15** [comment]
The link is walking https://learn-anything.xyz/

**Comment by SantoshKumar3295** [comment]
Bro can you help me with compilebox library?

**Comment by sdmg15** [comment]
Ok no problem but you should consider opening your  own issue. Thanks.
