### ISSUE TITLE
Due Credits ?

### ISSUE THREAD

**Issue by ashish2199** [sdmg15/Best-websites-a-programmer-should-visit#221]
I find many links taken directly from the answer, I wroteon Quora.
Is it true ? If yes, maybe you can mention it in there.

Lot of content is same as mine, even the description of the links.

[ My answer on Quora ](https://www.quora.com/What-are-the-best-websites-a-programmer-should-visit/answer/Ashish-Padalkar?srid=OH96)

**Comment by ityler** [comment]
I proposed a PR #229 to add credit to you for your initial contribution. After viewing the data in the initial commit to this repository and comparing this to your Quora post I think it's an absolute must that some credit is given where the initial data came from. Being one of the top contributors to this repository, though not the creator,  I feel it's a non-negotiable to not include at the least a call out to yourself and a link to the initial post in the repository README.

**Comment by ashish2199** [comment]
Thanks
