### ISSUE TITLE
Validation Links

### ISSUE THREAD

**Issue by kk-r** [sdmg15/Best-websites-a-programmer-should-visit#265]
@sdmg15 I checked most of the PRs failing because of redirect, ssl errors and 404/500 errors. 

1. Why can't we add --allow-ssl --allow-redirect in travis.yml. 
2. Shall we remove links which return 404/500.

Please let me know I can help with that. :slightly_smiling_face:

**Comment by sdmg15** [comment]
Hello, I don't know but sometime the build fails but the link is still working. 
It's why there're some links that I didn't remove.
But if there're other with that http code, yeah we can remove.

**Comment by rachmadaniHaryono** [comment]
hi @sdmg15, i just made pr for this based on recommendation from @kk-r 

with the new rule, some sites can be removed from white list, but it can be done on another pr
