### ISSUE TITLE
it-ebooks. 

### ISSUE THREAD

**Issue by arialdomartini** [sdmg15/Best-websites-a-programmer-should-visit#29]
I'm not 100% convinced it-ebooks.info is a legal website,since it contains copies of copyright books.
I would avoid suggesting it.

**Comment by arialdomartini** [comment]
I'm not 100% convinced it-ebooks.info is a legal website,since it contains copies of copyright books. 
I would avoid suggesting it.

**Comment by sdmg15** [comment]
Noted.
