### ISSUE TITLE
Google Code has shut down as of 2016

### ISSUE THREAD

**Issue by mph121** [sdmg15/Best-websites-a-programmer-should-visit#377]
Under open source websites, Google Code is now read only, you cannot add any new projects

**Comment by yemfol** [comment]
SUGGESTED, (EASY-TO-LEARN) PROGRAMMING WEBSITES.

(1) https://www.w3schools.com/

(2) https://www.quackit.com/

(3) https://www.pluralsight.com/

Hi!

Listed above are some of the (easy-to-learn) programming language (reference websites) that I think everyone would find useful.

I will continue to update the list as soon as I come across such websites while browsing.

(https://github.com/yemfol/hello-world/wiki)

(https://github.com/yemfol/hello-world/projects)

**Comment by filiptronicek** [comment]
I think this should be reopened, what is the reason for closing it? @sdmg15
