### ISSUE TITLE
Very bed messages

### ISSUE THREAD

**Issue by neo7BF** [sdmg15/Best-websites-a-programmer-should-visit#386]
I received very bed messages in my email from this repository. If happen yet I'll delete my subscription

**Comment by machinecp** [comment]
they are sending messages, other than things from this repository, I think it is a malicious attack

**Comment by sdmg15** [comment]
What are you talking about ? There is no email subscription. So whatever you received I'm not concerned.
Regards

**Comment by neo7BF** [comment]
below the technical description of the email received.
-------------------------------------------------------------

Delivered-To: XXXXX
Received: by 2002:a17:906:724a:0:0:0:0 with SMTP id n10csp5169179ejk;
        Thu, 27 Feb 2020 14:39:16 -0800 (PST)
X-Google-Smtp-Source: APXvYqxgMiFPd5PrjFD4w5CvX+rzT5MWA4Pz3FmTO1J91Qvd6cZvJ/kLJXLeA2HY1eY4bVeskfFY
X-Received: by 2002:adf:ed04:: with SMTP id a4mr1081769wro.76.1582843156358;
        Thu, 27 Feb 2020 14:39:16 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1582843156; cv=none;
        d=google.com; s=arc-20160816;
        b=Y5h6c8W46TXsLXI/CVZAStJT7q5j8qF1wCvzzb7+jeMX2othb9PI0Tpa0WAylSwVyh
         sk6c46TeqArk9bLzcbISCbIlhwga82UE1kCr6vrxdRaOC7nE2cP3SLNyc1L/MzzPuYZ7
         ciAg4ZunwtqXpfX+6B7yH/BXkeTIQlxN/JSVp/H+AtkJEJBT92JeQmhFhl+tmXgevRIP
         LeCDqrzIq+4vPTOepdeoDViCv2IlNdwlMjvwIDjCyNQeB7WueZ+WLSZCpQqdXyjiov0H
         9Zs5MlWDo6pzw45cXMMOkvFpEIoz3WzkkKkZAl0LtD9ea+1neY4WNEX9UHxk/EGO8pZk
         ZrBg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:message-id:cc:to
         :reply-to:from:dkim-signature:date;
        bh=PwXAmxJ4lahCl3t+5nW24N5MDRXgh369KBCVfSca9dY=;
        b=vWjR6C2H0LKE1LbwcgahfWsCRrRwTKiR8WvTfOI7zO/tn/959ehf2OmcGMOwRxvcVK
         28dMDH2qBkCHpaOYTZruIOMHcHv7FakTnd6Z2F5kAtGhi1ySV+Fa+29DPQU58pi5HeqA
         cbGfsBzEUfXZz9ADqsg7fcGT+kPoKT+kI0/t53XvEayY52oJ8cksc750lze/Brv1iGgR
         xC29u9xiifkPWi88QidlI4Jh1CbFtbei/fWQfgxjsUZ5ZUpO8FIzh7T7wDU4VGt6zTHl
         5JIKBgvfbW8R9was6Vh/ArHMxiTU07JTek+STpoc3q2UdoQsTBl3HiG/4YQrQ4ZtLDPh
         SEoQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=jKlRlC9B;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.202 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Return-Path: <noreply@github.com>
Received: from out-19.smtp.github.com (out-19.smtp.github.com. [192.30.252.202])
        by mx.google.com with ESMTPS id h8si889219wrq.146.2020.02.27.14.39.16
        for <XXXXXXXXXXXXXXX>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 27 Feb 2020 14:39:16 -0800 (PST)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.202 as permitted sender) client-ip=192.30.252.202;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=jKlRlC9B;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.202 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Thu, 27 Feb 2020 14:39:15 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com; s=pf2014; t=1582843155; bh=PwXAmxJ4lahCl3t+5nW24N5MDRXgh369KBCVfSca9dY=; h=Date:From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From; b=jKlRlC9B5pSR+39z5iKxpI+xmekHw5PWNKf0s5/rf3tRPqS+rf62H12HIHeM1TJCM
	 aiURptUKK+IYf2h0x4xjUzldCKllfH1kWpwW8pGOq0w8I03YEQ1oVRUzK0UGf7NfWE
	 UR/Qk3YS6upIlrIygKOrzQfbVu7zIaC5FOBg9ETs=
