### ISSUE TITLE
Please add command line and shell scripting

### ISSUE THREAD

**Issue by kitgary** [sdmg15/Best-websites-a-programmer-should-visit#49]
I have been frustrated by shell scripting for a long time, those linux commands such as grep, sed, awk are just too difficult to learn, shell scripts look like kind of magic to me.

**Comment by sdmg15** [comment]
I don't really get what you're asking for. Are you talking about resources on that ?

**Comment by sdmg15** [comment]
@kitgary Are you satisfy ?
