### ISSUE TITLE
Improvise CONTRIBUTING.md

### ISSUE THREAD

**Issue by yugrajani** [sdmg15/Best-websites-a-programmer-should-visit#566]
In the spirit of getting more contributors for this project during the Hacktoberfest, detailed steps to contribute for beginners written in CONTRIBUTING.md file would be highly appreciated and would prove to be a good guide for new comers to open source.

**Comment by yugrajani** [comment]
Hey @sdmg15, may I work on this issue?

**Comment by rAwsam** [comment]
hey there may i work on the issue

**Comment by HarmanBhutani** [comment]
Hi , can I work on given issue?

**Comment by sdmg15** [comment]
Yes you can, it should be noted inside that only one link or max two per pull requests.

**Comment by oshyam** [comment]
Hi, I would like to contribute.
