### ISSUE TITLE
Multisub Incorrectly Linked

### ISSUE THREAD

**Issue by aidancrane** [sdmg15/Best-websites-a-programmer-should-visit#6]
The section [everything in one place](https://github.com/sdmg15/Best-websites-a-programmer-should-visit#everything-in-one-place) is not linked correctly to a multi sub as it has 'reddit.com/me/' in, which refers to the current logged in user. It should be something like,

> https://www.reddit.com/sdmg15/m/cs_student_subs

But that does not work either, which suggests that it is not your username.

**Comment by DavidBuchanan314** [comment]
I found this, I'm not sure if it was the one intended: https://www.reddit.com/user/ashish2199/m/cs_student_subs/

**Comment by sdmg15** [comment]
@DavidBuchanan314 Please make a PR for correction.
THX.

**Comment by DavidBuchanan314** [comment]
It would appear that someone has already fixed this issue.
