### ISSUE TITLE
Dead-Links

### ISSUE THREAD

**Issue by Sainithin-bit** [sdmg15/Best-websites-a-programmer-should-visit#774]
https://fly.io/articles/why-fast-pages-are-important/
https://fly.io/articles/why-fast-pages-are-important/
https://github.com/sdmg15/Best-websites-a-programmer-should-visit/blob/master/unchainedpodcast.co
http://www.eclipse.org/org/foundation/eclipselabs/faq.php

**Comment by Sainithin-bit** [comment]
Can I submit a PR removing all above links

**Comment by sdmg15** [comment]
Yes for sure !

**Comment by Sainithin-bit** [comment]
Ok!
I submitted  a PR  #775
