### ISSUE TITLE
gitignore is not coding practice for beginners.

### ISSUE THREAD

**Issue by alecgirman** [sdmg15/Best-websites-a-programmer-should-visit#780]

**Comment by sdmg15** [comment]
Hello, please can you be more explicit

**Comment by alecgirman** [comment]
Under coding practice, you have [gitignore](https://www.gitignore.io/) listed, but it is more of a general resource rather than a place to learn and practice code.

**Comment by sdmg15** [comment]
Yeah you are right, thanks for reporting, if you can open a PR to move it into another it will be great!
