### ISSUE TITLE
Adding a Learning networks section

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [sdmg15/Best-websites-a-programmer-should-visit#886]
Learning computer networks using simulation tools, network and port analysing tools with practical guides that help with each step
[All free resources added]

**Comment by Maykkkk** [comment]
hey, I can help you in this. Is this contribution counts in hacktoberfest?

**Comment by sdmg15** [comment]
Hey @Maykkkk,
 you can go ahead and create another Pull Request with the changes you want to be merged
