### ISSUE TITLE
Adding a Navbar on the landing page of Websites

### ISSUE THREAD

**Issue by priyanshu688** [sdmg15/Best-websites-a-programmer-should-visit#905]
here we add the navbar with some dynamic effect on the background using react.js and node.js

**Comment by priyanshu688** [comment]
@sdmg15 Hey can you please tell me whether Can I work on this issue ?

**Comment by sdmg15** [comment]
Okay go ahead

**Comment by Devanshu236** [comment]
i can contribute to this project i get a chance to
